spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
